services:
  # Backend Service
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: backend/Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: DB_HOST
        value: dpg-d6r7diruibrs739jv71g-a
      - key: DB_USER
        value: todo_database_c1um_user
      - key: DB_PASSWORD
        value: 87n2SIUx4PMc3858jVcDMAoQ1O01Yn8C
      - key: DB_NAME
        value: todo_database_c1um
      - key: DB_PORT
        value: 5432
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production

  # Frontend Service
  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: frontend/Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: be-todo
          property: host
